name: Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync.yml
      - workspace/sync/**/*
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: FRONTMATTER_BOT
    strategy:
      fail-fast: false
      matrix:
        repo:
          - trustwallet/assets
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version-file: '.nvmrc'

      - run: corepack enable pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm turbo run build
        working-directory: workspace/sync

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: workspace/sync/repo
          repository: ${{ matrix.repo }}
          ref: master

      - run: pnpm run sync ${{ matrix.repo }}
        working-directory: workspace/sync

      - id: app
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.FRONTMATTER_BOT_APP_ID }}
          private_key: ${{ secrets.FRONTMATTER_BOT_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ steps.app.outputs.token }}
          commit-message: 'chore(sync): ${{ matrix.repo }}'
          title: 'chore(sync): ${{ matrix.repo }}'
          committer: Frontmatter Bot <frontmatter-bot@users.noreply.github.com>
          author: Frontmatter Bot <frontmatter-bot@users.noreply.github.com>
          body: |
            #### What this PR does / why we need it:

            Sync latest changes from `${{ matrix.repo }}` repository using `@workspace/sync`.

          branch: sync/${{ matrix.repo }}
