name: Sync

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/sync-trustwallet-assets.yml
      - workspace/sync-trustwallet-assets/**/*
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: FRONTMATTER_BOT
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version-file: '.nvmrc'

      - run: corepack enable pnpm

      - run: pnpm install --frozen-lockfile

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          path: workspace/sync-trustwallet-assets/repo
          repository: trustwallet/assets
          ref: master

      - run: pnpm turbo run sync
        working-directory: workspace/sync-trustwallet-assets

      - id: app
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.FRONTMATTER_BOT_APP_ID }}
          private_key: ${{ secrets.FRONTMATTER_BOT_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ steps.app.outputs.token }}
          commit-message: 'chore(sync): trustwallet/assets'
          title: 'chore(sync): trustwallet/assets'
          committer: Frontmatter Bot <frontmatter-bot@users.noreply.github.com>
          author: Frontmatter Bot <frontmatter-bot@users.noreply.github.com>
          body: |
            #### What this PR does / why we need it:

            Sync latest changes from `trustwallet/assets` repository.

          branch: sync/trustwallet/assets
